### ISSUE TITLE
Is there a reason these lines are repeated twice?

### ISSUE THREAD

**Issue by arokem** [aculich/rockyter#1]
https://github.com/aculich/rockyter/blob/6651ccc44c85498086dd76819a1033809234ce85/Dockerfile#L26-L27

**Comment by aculich** [comment]
If you look closely you'll see that, though they look very similar, they are actually two different repos that have similar names:

- server proxy:     https://github.com/jupyterhub/nbserverproxy
- r session proxy: https://github.com/jupyterhub/nbrsessionproxy

https://github.com/aculich/rockyter/blob/6651ccc44c85498086dd76819a1033809234ce85/Dockerfile#L26-L30

**Comment by arokem** [comment]
Nobody has time to read all the letters :-) 

Thanks!
